export type TasksModelState = {
	collection: { [taskId: string]: TaskModel },
};

export type TaskModel = {
	id: number,
	title: string,
	isImportant: boolean,
	description: string,
	creatorId: number,
	createdTs: number,
	responsibleId: number,
	deadlineTs: number,
	needsControl: boolean,
	fileIds: number[],
	checklist: [],
	containsChecklist: boolean,
	groupId: number,
	stageId: number,
	storyPoints: string,
	epicId: number,
	flowId: number,
	status: string,
	statusChangedTs: string,
	accomplicesIds: number[],
	auditorsIds: number[],
	chatId: number,
	filledFields: { [field: string]: boolean },
	rights: TaskRights,
};

export type TaskRights = {
	read: boolean,
	edit: boolean,
	remove: boolean,
	complete: boolean,
	approve: boolean,
	disapprove: boolean,
	start: boolean,
	take: boolean,
	delegate: boolean,
	defer: boolean,
	renew: boolean,
	create: boolean,
	deadline: boolean,
	changeDirector: boolean,
	changeResponsible: boolean,
	changeAccomplices: boolean,
	pause: boolean,
	timeTracking: boolean,
	rate: boolean,
	changeStatus: boolean,
	reminder: boolean,
	addAuditors: boolean,
	elapsedTime: boolean,
	favorite: boolean,
	checklistAdd: boolean,
	checklistEdit: boolean,
	checklistSave: boolean,
	checklistToggle: boolean,
	automate: boolean,
	resultEdit: boolean,
	completeResult: boolean,
	removeResult: boolean,
	admin: boolean,
	watch: boolean,
	mute: boolean,
	createSubtask: boolean,
	copy: boolean,
	createFromTemplate: boolean,
	saveAsTemplate: boolean,
};
