<?php

return [
	'extensions' => [
		'type',
		'loc',
		'entity-ready',
		'utils/object',
		'list/selector',
		'pull/client/events',
		'statemanager/vuex',
		'statemanager/vuex-manager',
		'im:messenger/component/messenger-base',
		'im:chat/timer',
		'im:chat/selector/adapter/dialog-list',
		'im:messenger/core/collab',
		'im:messenger/const',
		'im:messenger/lib/helper',
		'im:messenger/lib/params',
		'im:messenger/controller/recent/collab',
		'im:messenger/controller/dialog/chat',
		'im:messenger/controller/dialog/lib/assets',
		'im:messenger/controller/chat-creator',
		'im:messenger/controller/forward-selector',
		'im:messenger/controller/dialog-creator',
		'im:messenger/view/recent',
		'im:messenger/lib/logger',
		'im:messenger/lib/counters/tab-counters',
		'im:messenger/model',
		'im:messenger/view/dialog',
		'im:messenger/provider/pull/chat',
		'im:messenger/provider/pull/collab',
		'im:messenger/provider/pull/vote',
		'im:messenger/provider/services/messenger-init',
		'im:messenger/provider/services/sync/fillers/collab',
		'im:messenger/provider/services/analytics',
		'im:messenger/lib/rest-manager',
		'im:messenger/lib/integration/mobile/communication',
		'im:messenger/lib/promotion',
		'im:messenger/lib/notifier',
		'im:messenger/lib/emitter',
		'im:messenger/lib/visibility-manager',
		'im:messenger/lib/ui/header/icon',
		'im:messenger/widgets/user-profile',
		'im:messenger/widgets/participants-list',
		'im:messenger/lib/ui/header',
		'im:messenger/controller/search/experimental',
		'im:messenger/lib/feature',
		'im:messenger/lib/smile-manager',
		'im:messenger/lib/di/service-locator',
		'im:messenger/controller/sidebar-v2/factory',
		'im:messenger/lib/quick-recent-load',
	],
	'components' => [],
	//'packer' => [],
];
