<?
$MESS["DISK_HELP_0"] = "Dokumentenverwaltung in Bitrix24";
$MESS["DISK_HELP_1"] = "<strong>Drive</strong> ist ein Werkzeug, mit dem Sie Ihre Dokumentenverwaltung systematisieren können. Das ist Ihr Datei-Speicher, wo Sie Dateien gemeinsam mit Ihren Kollegen bearbeiten können. Sie können Dateien austauschen, im Activity Stream veröffentlichen und darüber diskutieren.";
$MESS["DISK_HELP_2"] = "Arbeit mit Dateien";
$MESS["DISK_HELP_3"] = "So erstellen Sie ein neues Dokument";
$MESS["DISK_HELP_4"] = "Was ist Bitrix24.Drive und wozu ist das gut";
$MESS["DISK_HELP_5"] = "So können Sie an Dokumenten gemeinsam arbeiten";
$MESS["DISK_HELP_6"] = "So stellen Sie fest, wo ein Dokument bereits veröffentlicht wurde";
$MESS["DISK_HELP_7"] = "Arbeit mit Dateien";
$MESS["DISK_HELP_8"] = "Drive bietet eine einfache und intuitiv verständliche Navigation mit der Baumstruktur an. Es gibt zwei Ansicht-Modi: Flat Design und Kacheln-Ansicht, die Letztere ist für die Arbeit mit Bildern besonders gut geeignet.";
$MESS["DISK_HELP_9"] = "So erstellen Sie ein neues Dokument";
$MESS["DISK_HELP_10"] = "Sie können neue Dateien hochladen oder sie online erstellen. Drive ermöglicht es Ihnen, mehrere Dateien gleichzeitig hochzuladen. Auch per drag&drop können Dateien verschoben werden. Dabei müssen Sie lediglich auf die Schaltfläche «Hochladen» klicken oder gewünschte Dokumente mit der Maus verschieben ? und schon sind sie in Ihrem Drive. Zur Erstellung neuer Dokumente können Sie GoogleDocs oder MS Office Web App benutzen, oder auch übliche Programme wie etwa MS Office.";
$MESS["DISK_HELP_11"] = "Was ist Bitrix24.Drive und wozu ist das gut";
$MESS["DISK_HELP_12"] = "Bitrix24.Drive ist ein Tool, mit dessen Hilfe Sie Ihre Dokumente zwischen Ihrem Bitrix24 und Ihrem Computer stets synchronisieren können: alle gemachten Änderungen werden übernommen und das aktuelle Dokument wird in beiden Orten gespeichert. Sie müssen das Dokument, in dem Sie Änderungen vornehmen, nicht herunterladen und wieder hochladen ? es reicht, wenn Sie es einmal öffnen, ändern und speichern. Um Bitrix24.Drive aktivieren und für die Arbeit mit Dokumenten nutzen zu können, müssen Sie die Bitrix24 Desktop-Anwendung herunterladen und installieren.";
$MESS["DISK_HELP_13"] = "So können Sie an Dokumenten gemeinsam arbeiten";
$MESS["DISK_HELP_14"] = "Arbeit mit Dokumenten (Veröffentlichung und Diskussion) ist auch im Activity Stream möglich. Sie können dort eine neue Nachricht schreiben und eine Datei zur Nachricht anhängen, sodass Ihre Kollegen sich diese Datei anschauen und bei Bedarf auch bearbeiten können. Sobald jemand die Datei ändert, ändert sich auch die ursprüngliche Datei in der Nachricht, während die vorherigen Versionen in den Kommentaren verfügbar bleiben. Neue Empfänger bekommen in der Nachricht stets ein aktuelles Dokument angezeigt, können aber auch die Versionen in den Kommentaren sehen.";
$MESS["DISK_HELP_15"] = "Sie müssen nun Dokumente weder herunterladen noch hochladen, um darin etwas zu ändern";
$MESS["DISK_HELP_16"] = "Sind Sie nicht berechtigt, ein Dokument zu bearbeiten, und bekommen es aber trotzdem im Activity Stream, können Sie dieses Dokument öffnen und ändern: Nachdem Sie die Änderungen speichern, wird Ihre Version des Dokuments als eine extra Datei an Ihren Kommentar angehängt. Haben Sie entsprechende Rechte und können Dokument sofort bearbeiten, wird das ursprüngliche Dokument schon in der Nachricht selbst aktualisiert und geändert, während die vorherigen Versionen in früheren Kommentaren gefunden werden können.";
$MESS["DISK_HELP_17"] = "So stellen Sie fest, wo ein Dokument bereits veröffentlicht wurde";
$MESS["DISK_HELP_18"] = "Informationen darüber, wo Ihr Dokument angehängt bzw. veröffentlicht wurde (ob im Activity Stream, in Aufgaben, im Kalender etc.) sowie darüber, welche Nutzer auf dieses Dokument zugreifen können, finden Sie unter Dateieigenschaften. Wenn Sie eine Datei in Ihrem Drive löschen, löschen Sie diese innerhalb des ganzen Systems: Die Datei verschwindet aus allen Ereignissen, wo sie früher angehängt war.";
$MESS["DISK_HELP_19"] = "<strong>Drive</strong> ist ein Tool, mit dem Sie die Dokumentenverwaltung einfach, schnell und bequem gestalten können. Nähere Informationen über Drive finden Sie im Trainingskurs.";
?>