<?php

if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();

use Bitrix\Crm\Component\EntityDetails\FactoryBased;
use Bitrix\Crm\Integration\UI\EntityEditor\DefaultEntityConfig\SmartDocumentDefaultEntityConfig;
use Bitrix\Crm\Item;
use Bitrix\Crm\Service\EditorAdapter;
use Bitrix\Main\Loader;
use Bitrix\Main\Localization\Loc;
use Bitrix\Main\Web\Uri;

Loader::includeModule('crm');

class CrmSmartDocumentDetailsComponent extends FactoryBased
{
	public function getEditorEntityConfig(): array
	{
		return (new SmartDocumentDefaultEntityConfig($this->getEntityTypeID()))->get();
	}

	public function getInlineEditorEntityConfig(): array
	{
		$sections = [];
		$sections[] = [
			'name' => 'myCompany',
			'title' => Loc::getMessage('CRM_COMPONENTS_DOCUMENT_DETAILS_MY_COMPANY_SECTION_TITLE'),
			'type' => 'section',
			'elements' => [
				['name' => \Bitrix\Crm\Item::FIELD_NAME_MYCOMPANY_ID],
			],
		];
		if ($this->getEntityTypeID() === CCrmOwnerType::SmartB2eDocument)
		{
			return $sections;
		}

		$sections[] = [
			'name' => 'client',
			'title' => Loc::getMessage('CRM_COMPONENTS_DOCUMENT_DETAILS_CLIENT_SECTION_TITLE'),
			'type' => 'section',
			'elements' => [
				['name' => EditorAdapter::FIELD_CLIENT],
			],
		];

		return $sections;
	}

	public function executeComponent()
	{
		$this->init();

		if($this->getErrors())
		{
			$this->includeComponentTemplate();
			return;
		}

		$this->executeBaseLogic();

		$this->setBizprocStarterConfig();

		$this->includeComponentTemplate();
	}

	protected function getTabs(): array
	{
		$tabs = [];

		if ($this->arParams['ENTITY_TYPE_ID'] === \CCrmOwnerType::SmartB2eDocument)
		{
			$uri = '/bitrix/components/bitrix/sign.document.list/slider.php';

			$tabs[] = [
				'id' => 'tab_sign',
				'name' => \Bitrix\Main\Localization\Loc::getMessage('CRM_COMPONENTS_DOCUMENT_DETAILS_SIGN_PROCESS_BUTTON'),
				'slider' => [
					'uri' => $uri,
					'params' => [
						'site_id' => SITE_ID,
						'sessid' => bitrix_sessid_get(),
						'type' => 'document',
						'entity_id' => $this->arParams['ENTITY_ID'],
					],
					'sliderParams' => [
						'width' => 1000,
						'loader' => 'intranet:crm',
					]
				],
			];
			$tabs[] = $this->getDefaultTabInfoByCode(static::TAB_NAME_AUTOMATION);
			$tabs[] = $this->getDefaultTabInfoByCode(static::TAB_NAME_TREE);
			$tabs[] = $this->getDefaultTabInfoByCode(static::TAB_NAME_EVENT);
		}
		else
		{
			$tabs = parent::getTabs();
		}

		return $tabs;
	}

	protected function getEntityDetailsParams(): array
	{
		$detailParams =  parent::getEntityDetailsParams(); // TODO: Change the autogenerated stub
		if ($this->arParams['ENTITY_TYPE_ID'] === \CCrmOwnerType::SmartB2eDocument)
		{
			$detailParams['REST_USE'] = 'N';
		}

		return $detailParams;
	}
}
