<?php
$MESS["TASKS_BP_DOCUMENT_ENTITY_NAME"] = "Ағын";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_0"] = "[flowUrl]{flowName}[/flowUrl] ағынында {totalTasksInQueue} міндет күту үстінде. [groupUrl]{groupName}[/groupUrl] жобасында сіз қызметкерлерге жүктемені басқара аласыз";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_1"] = "[flowUrl]{flowName}[/flowUrl] ағынында {totalTasksInQueue} міндеттер күту үстінде. [groupUrl]{groupName}[/groupUrl] жобасында сіз қызметкерлерге жүктемені басқара аласыз";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_2"] = "[flowUrl]{flowName}[/flowUrl] ағынында {totalTasksInQueue} міндет күту үстінде. [groupUrl]{groupName}[/groupUrl] жобасында сіз қызметкерлерге жүктемені басқара аласыз";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_0"] = "[flowUrl]{flowName}[/flowUrl] ағынында {totalTasksInProgress} міндет жұмыс үстінде. [groupUrl]{groupName}[/groupUrl] жобасында сіз қызметкерлерге жүктемені басқара аласыз";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_1"] = "[flowUrl]{flowName}[/flowUrl] ағынында {totalTasksInProgress} міндет жұмыс үстінде. [groupUrl]{groupName}[/groupUrl] жобасында сіз қызметкерлерге жүктемені басқара аласыз";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_2"] = "[flowUrl]{flowName}[/flowUrl] ағынында {totalTasksInProgress} міндет жұмыс үстінде. [groupUrl]{groupName}[/groupUrl] жобасында сіз қызметкерлерге жүктемені басқара аласыз";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_EFFICIENCY_LOWER_MESSAGE"] = "[flowUrl]{flowName}[/flowUrl] ағынында тиімділік {targetEfficiency}%-дан төмен. Міндеттердің орындалу мерзімін бақылаңыз";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_ABSENT"] = "[flowUrl]{flowName}[/flowUrl] ағындағы міндеттерді бөлген қызметкер жоқ. Енді барлық міндеттер сізге тағайындалатын болады, міндеттерді бөлу әдісін [flowSettingsUrl]ағын баптауларында[/flowSettingsUrl] өзгертуге болады";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_MESSAGE"] = "[flowUrl]{flowName}[/flowUrl] ағындағы міндеттерді бөлген қызметкер жұмыстан босатылды. Енді барлық міндеттер сізге тағайындалатын болады, міндеттерді бөлу әдісін [flowSettingsUrl]ағын баптауларында[/flowSettingsUrl] өзгертуге болады";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_ABSENT_MESSAGE"] = "[flowUrl]{flowName}[/flowUrl] ағынында барлық міндеттер енді сізге бөлінеді, өйткені кезектегі қызметкерлердің барлығы жоқ. Орындаушыларды сіз [flowSettingsUrl]ағын баптауларында[/flowSettingsUrl] қоса аласыз";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_MESSAGE"] = "[flowUrl]{flowName}[/flowUrl] ағынында барлық міндеттер енді сізге бөлінеді, өйткені кезекте қызметкерлер қалмады. Орындаушыларды сіз [flowSettingsUrl]ағын баптауларында[/flowSettingsUrl] қоса аласыз";
