<?php

return [
	'extensions' => [
		'type',
		'loc',
		'utils/array',
		'utils/object',
		'im:messenger/lib/di/service-locator',
		'im:messenger/const',
		'im:messenger/cache/share-dialog',
		'im:messenger/lib/converter/data/message',
		'im:messenger/lib/converter/data/recent',
		'im:messenger/lib/element',
		'im:messenger/lib/helper',
		'im:messenger/lib/params',
		'im:messenger/lib/counters/tab-counters',
		'im:messenger/lib/parser',
		'im:messenger/lib/notifier',
		'im:messenger/lib/emitter',
		'im:messenger/lib/uuid-manager',
		'im:messenger/lib/logger',
		'im:messenger/provider/services/sync/service',
		'im:messenger/provider/services/vote',
		'im:messenger/provider/pull/lib/new-message-manager/base',
		'im:messenger/provider/pull/lib/file',
		'im:chat/utils',
		'im:chat/messengercommon',
		'im:messenger/provider/data',
	],
	'bundle' => [
		'./src/pull-handler',
		'./src/dialog',
		'./src/message',
		'./src/application',
		'./src/counter',
	],
];
